name: Postman Collection Workflow

on:
  push:
    branches: [ main ]

  workflow_dispatch:

  schedule:
    - cron: "30 2 * * *"     # 8:00 AM IST every day
    - cron: "0 14 * * *"     # 7:30 PM IST every day
    - cron: "0 6 * * 1-5"    # 11:30 AM IST Monday–Friday

jobs:
  run-postman-tests:
    runs-on: ubuntu-latest   # ✅ GitHub Linux VM

    steps:
      - name: Checkout the code
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Install Newman and HTML Extra reporter
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra

      - name: Run Postman collection with Newman
        run: |
          mkdir -p newman
          newman run "Inwarranty-flow Collection.postman_collection.json" \
            -e QA.postman_environment.json \
            -d testData.csv \
            -r cli,htmlextra \
            --reporter-htmlextra-export newman/index.html

      - name: Upload Newman Report (Artifact)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Newman-HTML-Report
          path: newman/index.html

      - name: Publish report to GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: newman

      - name: Send Email Notification
        if: always()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          secure: true
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: Phoenix Inwarranty Flow – Test Execution Report
          to: viraj.kolekar6767@gmail.com
          from: ${{ secrets.EMAIL_USERNAME }}
          body: |
            Hi,

            Phoenix Inwarranty Flow Postman tests have been executed.

            The HTML report is published here:
            https://virajk-dev.github.io/Phoenix-Inwarranty-Flow/

            Regards,
            GitHub Actions
